favicon: /images/favicon.png
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/webstack_icon_producthunt.png
  collapsed: /images/collapsed.png
  dark:

flag:
  icon: flag-cn
  name: Chinese

search: true

githubCorner: '<a href="https://github.com/ql-isaac" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 个人站点
    icon: far fa-star
    config: 个人站点
  - name: 个人常用
    icon: far fa-star
    config: 个人常用
  - name: 优秀项目
    icon: far fa-star
    config: 优秀项目
  - name: 优质软件
    icon: far fa-star
    config: 优质软件
  - name: 参考资料
    icon: far fa-star
    config: 参考资料
  - name: 电子游戏
    icon: far fa-star
    config: 电子游戏
  - name: 素材资源
    icon: far fa-star
    submenu:
      - name: 图片素材
        icon: fas fa-tools
        config: 图片素材
      - name: 渐变配色
        icon: fas fa-tools
        config: 渐变配色
  - name: 开发工具
    icon: fas fa-tools
    config: 开发工具

个人站点:
  - name: ql-isaac
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/favicon-q.png
    url: https://ql-isaac.cn/
    description:
  - name: ql's HexoBlog
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/favicon-b.png
    url: https://blog.ql-isaac.cn/
    description:
  - name: ql's space
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/favicon-s.png
    url: https://space.ql-isaac.cn/
    description:
  - name: ql's nav
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/favicon-n.png
    url: /
    description:

个人常用:
  - name: 幕布
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/幕布.jpg
    url: https://mubu.com/app
    description: 不只是大纲笔记，更是一种思考方式。
  - name: 对象存储（七牛云）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/七牛云.jpeg
    url: https://portal.qiniu.com/kodo/bucket/resource?bucketName=ql-isaac
    description: 使用的第一个图床。
  - name: 头像（Gravatar）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/Gravatar.png
    url: https://cn.gravatar.com/emails
    description: 绑定邮箱的全球通用头像。
  - name: 网页在线通讯（DaoVoice）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/DaoVoice.jpg
    url: http://dashboard.daovoice.io/app/006213f1/settings/general
    description:
  - name: CDN（腾讯云）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/腾讯云.jpg
    url: https://console.cloud.tencent.com/cdn/domains
    description: 内容分发网络，加速我的基于 Hexo 的静态网站。
  - name: 站长统计（友盟）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/友盟.jpeg
    url: https://web.umeng.com/main.php?c=site&a=show
    description: U-Web - 网站流量统计分析工具
  - name: 静态网站托管（Vercel）
    img: https://ae01.alicdn.com/kf/Hfe6251603ed446848e99364bafeff3d7n.png
    url: https://vercel.com/dashboard/projects
    description: 曾经的 zeit，速度还可以。
  - name: 静态网站托管（Netlify）
    img: https://ae01.alicdn.com/kf/H68cb1b17450c401e9edcfaf88fea4446M.png
    url: https://www.netlify.com/
    description: 免费服务，速度稍稍有点慢。
  - name: 云服务（LeanCloud）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/LeanCloud.png
    url: https://console.leancloud.cn/apps
    description: 用于评论系统。
  - name: DNS 云解析（阿里云）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/阿里云.png
    url: https://dns.console.aliyun.com/?spm=5176.12901015.0.i12901015.5265525cN9Hm3e#/dns/setting/ql-isaac.cn
    description: 域名解析
  - name: 国内测速（站长工具）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/站长之家.png
    url: https://tool.chinaz.com/speedtest/
    description: 博客国内测速
  - name: QQ 邮箱
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/QQ邮箱.jpg
    url: https://mail.qq.com/
    description:
  - name: 谷歌邮箱
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/谷歌邮箱.jpg
    url: https://mail.google.com/
    description:

优秀项目:
  - name: Twikoo
    img: /images/logos/github.png
    url: https://github.com/imaegoo/twikoo
    description: 一个简洁、安全、免费的静态网站评论系统。
  - name: Butterfly
    img: /images/logos/github.png
    url: https://github.com/jerryc127/hexo-theme-butterfly
    description: A Hexo Theme

优质软件:
  - name: ScreenToGif
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/ScreenToGif.png
    url: https://www.screentogif.com/
    description: GIF 录制
  - name: Carnac
    img: /images/webstack_icon_producthunt.png
    url: http://code52.org/carnac/
    description: 按键操作实时显示工具

参考资料:
  - name: 菜鸟教程
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/runoob.png
    url: https://www.runoob.com/
    description: 菜鸟教程

电子游戏:
  - name: 游戏免费拿（Epic）
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/Epic.jpg
    url: https://www.epicgames.com/store/zh-CN/free-games
    description: 每周白嫖，不玩也得拿。

图片素材:
  - name: iconfont
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/iconfont.png
    url: http://www.iconfont.cn/
    description: 阿里巴巴矢量图标库
  - name: 小康的 Font Awesome 5 图标速查
    img: https://ae01.alicdn.com/kf/H139ad2194f9547d7b43005c8e18f048cR.png
    url: https://dh.xiaokang.me/font5/
    description: 简单快速的使用 Font Awesome 5 图标
  - name: Font Awesome5图标库
    img: https://ae01.alicdn.com/kf/H139ad2194f9547d7b43005c8e18f048cR.png
    url: https://fontawesome.com/icons?d=gallery&g=hands&m=free
    description: 快速查询 Font Awesome5 的图标。
  - name: Pinterest
    img: https://ae01.alicdn.com/kf/H007c1d984d47401591376258699206a9j.png
    url: https://www.pinterest.com/
    description: 瀑布流的形式展现图片内容，无需用户翻页，新的图片不断自动加载在页面底端。
  - name: wallhaven顶部图
    img: https://ae01.alicdn.com/kf/Hf887c2db312d40d1b5d27297a1edbeedu.png
    url: https://wallhaven.cc/toplist?page=3
    description: Most popular uploaded Wallpapers
  - name: Unsplash
    img: https://ae01.alicdn.com/kf/H7a74de7359e04abf8d1f46cd1d1f4709E.png
    url: https://unsplash.com/
    description: Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos.
  - name: Colorhub
    img: https://ae01.alicdn.com/kf/H0d8df69ba23c4a2baac8b0fac568b33e6.png
    url: https://www.colorhub.me/
    description: 高清无版权图片（个人和商业用途免费）
  - name: Pexels
    img: https://ae01.alicdn.com/kf/H9a8321e954a74cd69b104685ae1eb185t.png
    url: https://www.pexels.com/zh-cn/
    description: 免费素材照片，可以在任何地方使用。免费用于商业用途，无需注明归属。
  - name: Pixabay
    img: https://ae01.alicdn.com/kf/Hf57f57b587d44f3f97ad41ca64ef9617B.png
    url: https://pixabay.com/
    description: Stunning free images & royalty free stock
  - name: WallpaperHub
    img: https://ae01.alicdn.com/kf/He027a64143464cc6ae5dbfbc3f589b795.png
    url: https://wallpaperhub.app/
    description: Download free wallpapers for your PC, phone and tablet.
  - name: Behance
    img: https://ae01.alicdn.com/kf/Hf346fa9eae04495ea907707c4e6ba130g.png
    url: https://www.behance.net/
    description: Behance 作品精选
  - name: 站酷 (ZCOOL)
    img: https://ae01.alicdn.com/kf/H00876c41539945cdbf3ddef8e09450b9r.png
    url: https://www.zcool.com.cn/
    description: 站酷 (ZCOOL)，中国设计师互动平台。深耕设计领域十四年，站酷聚集了 1100 万设计师、摄影师、插画师、艺术家、创意人，设计创意群体中具有较高的影响力与号召力。
  - name: 特效背景生成
    img: /images/webstack_icon_producthunt.png
    url: https://coolbackgrounds.io/
    description: Cool Backgrounds
  - name: 拟物风格生成
    img: /images/webstack_icon_producthunt.png
    url: https://neumorphism.io/
    description: Generate Soft-UI CSS code
  - name: Backiee
    img: https://files.alexhchu.com/2020/08/18/293e8388a6a9a.png
    url: https://backiee.com/
    description: The ultimate free wallpaper site and app. Available on Web, iPhone, Android, Xbox, and Windows platform as well.
  - name: Desktop Wallps
    img: https://files.alexhchu.com/2020/08/18/280462535a19d.png
    url: http://desktop.hdwallps.com/
    description: HD Wallpaper For Desktop Background
  - name: wallpaperaccess
    img: https://files.alexhchu.com/2020/08/18/280462535a19d.png
    url: https://wallpaperaccess.com/
    description: Only the best wallpapers. Daily additions of new, awesome, HD wallpapers for desktop and phones.

渐变配色:
  - name: peise
    img: https://ae01.alicdn.com/kf/Hfd1b76bfbfa448eb84132a08feb75468Y.png
    url: http://www.peise.net/
    description: 在线配色
  - name: webkul
    img: https://ae01.alicdn.com/kf/Hebaaa27db8974449ad28d818d5660fb15.png
    url: https://webkul.github.io/coolhue/
    description: Get coolest handpicked gradient colors collection palette for your next project, alternatively copy css or download as image too.
  - name: uigradients
    img: https://ae01.alicdn.com/kf/H9231fd2d81e04b2a9e705e7261e5aeb5E.png
    url: https://uigradients.com/
    description: uiGradients is a handpicked collection of beautiful color gradients for designers and developers.
  - name: adobe color
    img: https://ae01.alicdn.com/kf/Hca2e611ffa2e413ba5d892dc2404ad0a4.png
    url: https://color.adobe.com/
    description: Adobe 家的配色

开发工具:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台
  - name: Gitee
    url: https://gitee.com/
    img: https://cdn.jsdelivr.net/gh/isaac-ql/nav-images-1/Gitee.png
    description: 唯一的优点：访问快？
  - name: CODING
    img: https://ae01.alicdn.com/kf/Hf4a158d295c948bfabf53e754048e569M.png
    url: https://isaac-ql.coding.net/user
    description: 一站式软件研发管理协作平台

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: <blockquote><p>本站是<a href="https://ql-isaac.cn/">ql-isaac</a>的个人网址导航。</p></blockquote>
  webmaster:
    head: 关于站长
    name: ql-isaac
    url: https://ql-isaac.cn/
    img: https://image.ql-isaac.cn/站长头像.jpg
    description: It's beautiful day!
    html: ''

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
